services:
  frontend:
    image: ghcr.io/ssciwr/onehealth-map-frontend:global_map_with_month_selector
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/etc/nginx/ssl:ro # Mount the certificate directory as read-only
    logging:
      driver: "local"
      options:
        max-size: 20m
        max-file: 25
